export const TableData = [
    '*','1','1','1','1','-','1','2','0','0','0','0','0','-','-','0','0','0','0','0','0','0','2',
    '1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','-','1',
    '1','1','1','1','1','1','2','0','0','2','2','0','-','0','2','0','2','1','1','1','0','1','2',
    '1','1','1','1','1','0','1','1','1','1','1','1','1','0','1','2','1','1','1','1','-','1','1',
    '1','1','1','1','1','0','1','1','1','1','1','1','-','0','2','2','1','1','1','1','-','1','1',
    '1','1','1','1','1','0','1','1','1','1','1','-','-','0','-','0','1','1','1','-','-','2','1',
    '1','1','1','1','1','0','-','-','-','0','0','0','-','0','0','0','0','0','-','-','0','0','1',
    '1','1','1','1','1','2','2','2','2','2','0','-','0','0','-','0','2','-','-','-','0','0','0',
    '1','1','1','1','1','2','0','2','1','1','1','1','1','2','-','2','1','1','1','1','1','1','0',
    '1','1','1','1','1','2','2','0','2','-','0','-','-','0','0','0','0','-','-','-','0','0','0',
    '0','1','1','1','1','0','0','2','-','0','0','-','-','-','-','0','0','-','-','-','0','-','0',
    '1','0','1','1','1','0','0','0','2','0','0','0','0','0','0','0','0','2','0','0','0','0','0',
    '1','1','1','1','1','0','0','2','1','0','0','0','-','-','-','0','-','-','-','-','0','-','2',
    '1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1'
];

export const NameData = {
    col: [
        `OH<sup class="blue"><small>-</small></sup>`,
        `NO<sub><small>3</small></sub><sup class="blue"><small>-</small></sup>`,
        `F<sup class="blue"><small>-</small></sup>`,
        `Cl<sup class="blue"><small>-</small></sup>`,
        `Br<sup class="blue"><small>-</small></sup>`,
        `I<sup class="blue"><small>-</small></sup>`,
        `S<sup class="blue"><small>2-</small></sup>`,
        `SO<sub><small>3</small></sub><sup class="blue"><small>2-</small></sup>`,
        `SO<sub><small>4</small></sub><sup class="blue"><small>2-</small></sup>`,
        `CO<sub><small>3</small></sub><sup class="blue"><small>2-</small></sup>`,
        `SiO<sub><small>3</small></sub><sup class="blue"><small>2-</small></sup>`,
        `PO<sub><small>4</small></sub><sup class="blue"><small>3-</small></sup>`,
        `CrO<sub><small>4</small></sub><sup class="blue"><small>2-</small></sup>`,
        `CH<sub><small>3</small></sub>COO<sup class="blue"><small>-</small></sup>`,
    ],
    row: [
        `H<sup class="red"><small>+</small></sup>`,
        `Li<sup class="red"><small>+</small></sup>`,
        `NH<sub><small>4</small></sub><sup class="red"><small>+</small></sup>`,
        `K<sup class="red"><small>+</small></sup>`,
        `Na<sup class="red"><small>+</small></sup>`,
        `Ag<sup class="red"><small>+</small></sup>`,
        `Ba<sup class="red"><small>2+</small></sup>`,
        `Ca<sup class="red"><small>2+</small></sup>`,
        `Mg<sup class="red"><small>2+</small></sup>`,
        `Zn<sup class="red"><small>2+</small></sup>`,
        `Mn<sup class="red"><small>2+</small></sup>`,
        `Cu<sup class="red"><small>2+</small></sup>`,
        `Cu<sup class="red"><small>+</small></sup>`,
        `Hg<sup class="red"><small>+</small></sup>`,
        `Hg<sup class="red"><small>2+</small></sup>`,
        `Pb<sup class="red"><small>2+</small></sup>`,
        `Fe<sup class="red"><small>2+</small></sup>`,
        `Fe<sup class="red"><small>3+</small></sup>`,
        `AI<sup class="red"><small>3+</small></sup>`,
        `Cr<sup class="red"><small>3+</small></sup>`,
        `Bi<sup class="red"><small>3+</small></sup>`,
        `Sn<sup class="red"><small>3+</small></sup>`,
        `Sr<sup class="red"><small>3+</small></sup>`,
    ]
};